<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.22000.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Win" Version="25.2.4" />
    <PackageReference Include="DevExpress.Win.Design" Version="25.2.4" />
    <PackageReference Include="Zzz.App.Service.Core" Version="8.0.1.10" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>

  <!-- Fichiers dans un sous-dossier (si applicable) -->
  <ItemGroup>
    <Compile Update="Controls\NavigationCtrl.cs" />
  </ItemGroup>

</Project>