<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22000.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>False</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="EventArgs\" />
    <Folder Include="Helpers\" />
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Win" Version="25.2.4" />
    <PackageReference Include="DevExpress.Win.Design" Version="25.2.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.3" />
    <PackageReference Include="Zzz.App.Service.Core" Version="8.0.1.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseWinform\BaseWinform.csproj" />
    <ProjectReference Include="..\Cataloger.Business\Cataloger.Business.csproj" />
    <ProjectReference Include="..\Cataloger.Core\Cataloger.Core.csproj" />
    <ProjectReference Include="..\Cataloger.DataAccess.Sqlite\Cataloger.DataAccess.Sqlite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="securite.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>